name: modern_charts
version: 0.1.13
author: Man Hoang <jolleekin@outlook.com>
description: A package for creating simple yet modern looking charts.
homepage: https://github.com/jolleekin/modern_charts
documentation: https://github.com/jolleekin/modern_charts/wiki/Docs
dependencies:
  intl: any
dev_dependencies:
  browser: any
environment:
  sdk: '>=2.0.0 <3.0.0'
